name: Sean Ye
author: Sean Ye
baseurl: https://seanyeschool.github.io/
description: 
github: https://github.com/SeanYeSchool
twitter: http://www.twitter.com/
itch: https://coolguyplayers.itch.io/
itchtwo: https://seen103.itch.io/
linkedin: http://www.linkedin.com
coding: https://seanyeschool.github.io//projects//coding_projects.html
renders: https://seanyeschool.github.io//projects//rendering_projects.html
projects: https://seanyeschool.github.io/projects/coding_projects.html

<!--https://seanyeschool.github.io/projects.html-->

email: rnpatel[at]me.com
location: 
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
